using System.Text.Json.Serialization;

namespace RPGGameMaster.Domain;

/// <summary>
/// A non-player character with a dynamically generated personality agent prompt.
/// </summary>
internal sealed class NPC : IEntity
{
    [JsonPropertyName("id")]
    public EntityId Id { get; set; } = EntityId.New();

    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("description")]
    public string Description { get; set; } = "";

    [JsonPropertyName("location_id")]
    public EntityId LocationId { get; set; }

    [JsonPropertyName("personality")]
    public string Personality { get; set; } = "";

    [JsonPropertyName("occupation")]
    public string Occupation { get; set; } = "";

    /// <summary>Concrete speech pattern description (e.g., "speaks in clipped military phrases").</summary>
    [JsonPropertyName("speaking_style")]
    public string SpeakingStyle { get; set; } = "";

    /// <summary>2-3 sentence personal history that informs the NPC's reactions.</summary>
    [JsonPropertyName("backstory")]
    public string Backstory { get; set; } = "";

    /// <summary>A hidden fact the NPC only reveals if the player earns trust.</summary>
    [JsonPropertyName("secret")]
    public string Secret { get; set; } = "";

    /// <summary>Current emotional state — mutated by player actions and world events.</summary>
    [JsonPropertyName("mood")]
    public string Mood { get; set; } = "neutral";

    /// <summary>
    /// Relationship score toward the player (-100 hostile to +100 devoted).
    /// Shifts via quest completion, dialogue, and combat near the NPC.
    /// </summary>
    [JsonPropertyName("disposition_toward_player")]
    public Disposition DispositionTowardPlayer { get; set; }

    /// <summary>
    /// Full system prompt for this NPC's dynamically created conversation agent.
    /// Generated by the NPC Weaver and stored with the NPC data.
    /// </summary>
    [JsonPropertyName("agent_instructions")]
    public string AgentInstructions { get; set; } = "";

    [JsonPropertyName("quests")]
    public List<Quest> Quests { get; set; } = [];

    [JsonPropertyName("has_met")]
    public bool HasMet { get; set; }

    /// <summary>
    /// Rolling dialogue history so the NPC remembers past conversations.
    /// Capped at <see cref="GameConstants.MaxLogEntries"/> to keep token budgets manageable.
    /// </summary>
    [JsonPropertyName("dialogue_history")]
    public List<string> DialogueHistory { get; set; } = [];

    public void AddDialogue(string entry)
        => DialogueHistory.AddCapped(entry, GameConstants.MaxLogEntries);
}
