using System.Text.Json.Serialization;

namespace RPGGameMaster.Models;

/// <summary>
/// A non-player character with a dynamically generated personality agent prompt.
/// </summary>
internal sealed class NPC
{
    [JsonPropertyName("id")]
    public string Id { get; set; } = Guid.NewGuid().ToString("N")[..8];

    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("description")]
    public string Description { get; set; } = "";

    [JsonPropertyName("location_id")]
    public string LocationId { get; set; } = "";

    [JsonPropertyName("personality")]
    public string Personality { get; set; } = "";

    [JsonPropertyName("occupation")]
    public string Occupation { get; set; } = "";

    /// <summary>
    /// Full system prompt for this NPC's dynamically created conversation agent.
    /// Generated by the NPC Weaver and stored with the NPC data.
    /// </summary>
    [JsonPropertyName("agent_instructions")]
    public string AgentInstructions { get; set; } = "";

    [JsonPropertyName("quests")]
    public List<Quest> Quests { get; set; } = [];

    [JsonPropertyName("has_met")]
    public bool HasMet { get; set; }

    /// <summary>
    /// Rolling dialogue history so the NPC remembers past conversations.
    /// Capped at <see cref="MaxDialogueEntries"/> to keep token budgets manageable.
    /// </summary>
    [JsonPropertyName("dialogue_history")]
    public List<string> DialogueHistory { get; set; } = [];

    public const int MaxDialogueEntries = 20;

    public void AddDialogue(string entry)
    {
        DialogueHistory.Add(entry);
        while (DialogueHistory.Count > MaxDialogueEntries)
            DialogueHistory.RemoveAt(0);
    }
}
