using System.Text.Json.Serialization;

namespace RPGGameMaster.Models;

/// <summary>
/// A combat move generated by the Combat Strategist agent.
/// Contains LLM-generated flavor + numeric modifiers that feed into CombatResolver.
/// </summary>
internal sealed class CombatMove : INumberedOption
{
    [JsonPropertyName("number")]
    public int Number { get; set; }  // set: reassigned in ParseMoves

    /// <summary>Short cinematic name, e.g. "Sweeping Blade Arc".</summary>
    [JsonPropertyName("name")]
    public string Name { get; init; } = "";

    /// <summary>One-sentence description of the move.</summary>
    [JsonPropertyName("description")]
    public string Description { get; init; } = "";

    /// <summary>Emoji icon for the move.</summary>
    [JsonPropertyName("icon")]
    public string Icon { get; init; } = "⚔️";

    /// <summary>attack, heavy, defensive, flee, item</summary>
    [JsonPropertyName("type")]
    public MoveType Type { get; init; } = MoveType.Attack;

    /// <summary>Bonus/penalty to the d20 attack roll. Clamped to [-3, +5].</summary>
    [JsonPropertyName("attack_bonus")]
    public int AttackBonus { get; init; }

    /// <summary>Bonus/penalty to damage dealt. Clamped to [-2, +8].</summary>
    [JsonPropertyName("damage_bonus")]
    public int DamageBonus { get; init; }

    /// <summary>Extra defense this round (reduces incoming damage). Clamped to [0, +5].</summary>
    [JsonPropertyName("defense_bonus")]
    public int DefenseBonus { get; init; }

    /// <summary>Self-damage from risky moves (e.g. reckless attacks). Clamped to [0, 10].</summary>
    [JsonPropertyName("self_damage")]
    public int SelfDamage { get; init; }
}
