using System.Text.Json.Serialization;

namespace RPGGameMaster.Models;

/// <summary>
/// An item that can be found, looted, bought, or used by the player.
/// </summary>
internal sealed class Item
{
    [JsonPropertyName("name")]
    public string Name { get; set; } = "";

    [JsonPropertyName("description")]
    public string Description { get; set; } = "";

    /// <summary>weapon, armor, potion, scroll, food, key, misc</summary>
    [JsonPropertyName("type")]
    public ItemType Type { get; set; } = ItemType.Misc;

    /// <summary>
    /// Positive number: damage bonus (weapon), armor bonus (armor), heal amount (potion/food).
    /// Zero for key/misc. Variable for scroll effects.
    /// </summary>
    [JsonPropertyName("effect_value")]
    public int EffectValue { get; set; }

    /// <summary>common, uncommon, rare, legendary — affects lore richness and examine detail.</summary>
    [JsonPropertyName("rarity")]
    public ItemRarity Rarity { get; set; } = ItemRarity.Common;

    /// <summary>Compute sell price based on item type and effect value.</summary>
    [JsonIgnore]
    public int SellPrice => Type.SellPrice(EffectValue);

    /// <summary>Whether the item can be actively used (scrolls, food, keys). Weapons/armor are passive.</summary>
    [JsonPropertyName("is_usable")]
    public bool IsUsable { get; set; }

    /// <summary>Whether using the item removes it from inventory (potions, scrolls, food = true; key = false).</summary>
    [JsonPropertyName("is_consumable")]
    public bool IsConsumable { get; set; }

    /// <summary>
    /// Rich lore description generated by the Item Sage agent on first examine.
    /// Cached here so re-examining doesn't re-generate.
    /// </summary>
    [JsonPropertyName("lore")]
    public string Lore { get; set; } = "";
}
